from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

from paziente.controller import controller_prenotazione

from tools.menu_a_tendina_paziente import MenuATendinaPaziente
from tools import ridimensiona_widget


class ViewPrenotazione(QWidget):

    def __init__(self, paziente, prenotazione, lista_prenotazioni):
        """
        Costruttore della classe ViewPrenotazione, nella quale vengono creati e mostrati tutti gli oggetti della
        Graphical User Interface (GUI) relativi alla suddetta view

        :param paziente: Variabile d'istanza che rappresenta un oggetto della classe Paziente
        :type paziente: Paziente
        :param prenotazione: Variabile d'istanza che rappresenta un oggetto della classe Prenotazione
        :type prenotazione: Prenotazione
        :param lista_prenotazioni: Variabile d'istanza che rappresenta la lista delle prenotazioni totali effettuate dai
                                    pazienti
        :type lista_prenotazioni: list
        """
        super().__init__()

        self.paziente = paziente
        self.prenotazione = prenotazione
        self.lista_prenotazioni = lista_prenotazioni

        self.le_mie_prenotazioni = QtWidgets.QLabel(self)
        self.logo = QtWidgets.QLabel(self)
        self.titolo = QtWidgets.QLabel(self)
        self.prenotazione_aperta = QtWidgets.QLabel(self)
        self.banner = QtWidgets.QLabel(self)
        self.nome = QtWidgets.QLabel(self)
        self.cognome = QtWidgets.QLabel(self)
        self.attivita_ambulatoriale = QtWidgets.QLabel(self)
        self.medico = QtWidgets.QLabel(self)
        self.data_e_ora = QtWidgets.QLabel(self)
        self.ambulatorio = QtWidgets.QLabel(self)
        self.prezzo = QtWidgets.QLabel(self)
        self.data_e_ora_prenotazione = QtWidgets.QLabel(self)
        self.nome_label = QtWidgets.QLabel(self)
        self.cognome_label = QtWidgets.QLabel(self)
        self.ambulatorio_label = QtWidgets.QLabel(self)
        self.attivita_ambulatoriale_label = QtWidgets.QLabel(self)
        self.medico_label = QtWidgets.QLabel(self)
        self.data_e_ora_label = QtWidgets.QLabel(self)
        self.prezzo_label = QtWidgets.QLabel(self)
        self.data_e_ora_prenotazione_label = QtWidgets.QLabel(self)
        self.torna_indietro = QtWidgets.QPushButton(self)
        self.download_pdf = QtWidgets.QPushButton(self)
        self.disdici = QtWidgets.QPushButton(self)
        self.setup_ui(self)

        self.menu_a_tendina = MenuATendinaPaziente(self)

        self.controller_prenotazione = controller_prenotazione.ControllerPrenotazione(self)

        ridimensiona_widget.ridimensiona_view(self)

    def setup_ui(self, prenotazioni_paziente):
        """
        Funzione che crea e determina le caratteristiche degli oggetti della ViewPrenotazione

        :param prenotazioni_paziente: Oggetto della view che rappresenta la view stessa
        :type prenotazioni_paziente: ViewPrenotazione
        """
        prenotazioni_paziente.setObjectName("prenotazioni_paziente")
        prenotazioni_paziente.move(0, 0)
        prenotazioni_paziente.resize(1920, 1080)
        prenotazioni_paziente.setMinimumSize(QtCore.QSize(1920, 1080))
        prenotazioni_paziente.setMaximumSize(QtCore.QSize(1920, 1080))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        prenotazioni_paziente.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Immagini/logo_casa_alfredo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        prenotazioni_paziente.setWindowIcon(icon)
        prenotazioni_paziente.setStyleSheet("")
        self.le_mie_prenotazioni.setGeometry(QtCore.QRect(530, 20, 981, 131))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.le_mie_prenotazioni.setFont(font)
        self.le_mie_prenotazioni.setStyleSheet("color: rgb(84, 149, 223);")
        self.le_mie_prenotazioni.setObjectName("le_mie_prenotazioni")
        self.logo.setGeometry(QtCore.QRect(10, 5, 110, 130))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("Immagini/logo_casa_alfredo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.titolo.setGeometry(QtCore.QRect(110, 20, 401, 110))
        self.titolo.setText("")
        self.titolo.setPixmap(QtGui.QPixmap("Immagini/titolo_casa_alfredo.png"))
        self.titolo.setScaledContents(True)
        self.titolo.setObjectName("titolo")
        self.prenotazione_aperta.setGeometry(QtCore.QRect(70, 190, 1731, 831))
        self.prenotazione_aperta.setStyleSheet("border: 2px solid;\n"
                                               "border-color: rgb(33, 97, 171);\n"
                                               "background-color: rgb(169, 202, 239);")
        self.prenotazione_aperta.setText("")
        self.prenotazione_aperta.setObjectName("prenotazione_aperta")
        self.banner.setGeometry(QtCore.QRect(72, 968, 1727, 51))
        self.banner.setStyleSheet("background-color: rgb(13, 41, 73);")
        self.banner.setText("")
        self.banner.setObjectName("banner")
        self.nome.setGeometry(QtCore.QRect(120, 250, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.nome.setFont(font)
        self.nome.setStyleSheet("color: rgb(13, 41, 73);")
        self.nome.setObjectName("nome")
        self.cognome.setGeometry(QtCore.QRect(120, 400, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.cognome.setFont(font)
        self.cognome.setStyleSheet("color: rgb(13, 41, 73);")
        self.cognome.setObjectName("cognome")
        self.attivita_ambulatoriale.setGeometry(QtCore.QRect(120, 700, 381, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.attivita_ambulatoriale.setFont(font)
        self.attivita_ambulatoriale.setStyleSheet("color: rgb(13, 41, 73);")
        self.attivita_ambulatoriale.setObjectName("attivita_ambulatoriale")
        self.medico.setGeometry(QtCore.QRect(960, 250, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.medico.setFont(font)
        self.medico.setStyleSheet("color: rgb(13, 41, 73);")
        self.medico.setObjectName("medico")
        self.data_e_ora.setGeometry(QtCore.QRect(960, 400, 191, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.data_e_ora.setFont(font)
        self.data_e_ora.setStyleSheet("color: rgb(13, 41, 73);")
        self.data_e_ora.setObjectName("data_e_ora")
        self.ambulatorio.setGeometry(QtCore.QRect(120, 550, 221, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.ambulatorio.setFont(font)
        self.ambulatorio.setStyleSheet("color: rgb(13, 41, 73);")
        self.ambulatorio.setObjectName("ambulatorio")
        self.prezzo.setGeometry(QtCore.QRect(960, 550, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.prezzo.setFont(font)
        self.prezzo.setStyleSheet("color: rgb(13, 41, 73);")
        self.prezzo.setObjectName("prezzo")
        self.data_e_ora_prenotazione.setGeometry(QtCore.QRect(960, 700, 421, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.data_e_ora_prenotazione.setFont(font)
        self.data_e_ora_prenotazione.setStyleSheet("color: rgb(13, 41, 73);")
        self.data_e_ora_prenotazione.setObjectName("data_e_ora_prenotazione")
        self.nome_label.setGeometry(QtCore.QRect(410, 250, 501, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.nome_label.setFont(font)
        self.nome_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.nome_label.setText("")
        self.nome_label.setObjectName("nome_label")
        self.cognome_label.setGeometry(QtCore.QRect(410, 400, 501, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.cognome_label.setFont(font)
        self.cognome_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.cognome_label.setText("")
        self.cognome_label.setObjectName("cognome_label")
        self.ambulatorio_label.setGeometry(QtCore.QRect(410, 550, 501, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.ambulatorio_label.setFont(font)
        self.ambulatorio_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.ambulatorio_label.setText("")
        self.ambulatorio_label.setObjectName("ambulatorio_label")
        self.attivita_ambulatoriale_label.setGeometry(QtCore.QRect(520, 700, 415, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(27)
        self.attivita_ambulatoriale_label.setFont(font)
        self.attivita_ambulatoriale_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.attivita_ambulatoriale_label.setText("")
        self.attivita_ambulatoriale_label.setObjectName("attivita_ambulatoriale_label")
        self.medico_label.setGeometry(QtCore.QRect(1240, 250, 501, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.medico_label.setFont(font)
        self.medico_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.medico_label.setText("")
        self.medico_label.setObjectName("medico_label")
        self.data_e_ora_label.setGeometry(QtCore.QRect(1240, 400, 501, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.data_e_ora_label.setFont(font)
        self.data_e_ora_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.data_e_ora_label.setText("")
        self.data_e_ora_label.setObjectName("data_e_ora_label")
        self.prezzo_label.setGeometry(QtCore.QRect(1240, 550, 501, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.prezzo_label.setFont(font)
        self.prezzo_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.prezzo_label.setText("")
        self.prezzo_label.setObjectName("prezzo_label")
        self.data_e_ora_prenotazione_label.setGeometry(QtCore.QRect(1400, 700, 360, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(29)
        self.data_e_ora_prenotazione_label.setFont(font)
        self.data_e_ora_prenotazione_label.setStyleSheet("color: rgb(33, 97, 171);")
        self.data_e_ora_prenotazione_label.setText("")
        self.data_e_ora_prenotazione_label.setObjectName("data_e_ora_prenotazione_label")
        self.torna_indietro.setGeometry(QtCore.QRect(85, 980, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.torna_indietro.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.torna_indietro.setFont(font)
        self.torna_indietro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.torna_indietro.setStyleSheet("QPushButton#torna_indietro {\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton#torna_indietro:pressed {\n"
                                          "background-color: rgb(0, 0, 0, 0);\n"
                                          "color: rgb(200, 200, 200);\n"
                                          "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Immagini/indietro bianco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.torna_indietro.setIcon(icon2)
        self.torna_indietro.setFlat(True)
        self.torna_indietro.setObjectName("torna_indietro")
        self.download_pdf.setGeometry(QtCore.QRect(845, 980, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.download_pdf.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.download_pdf.setFont(font)
        self.download_pdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_pdf.setStyleSheet("QPushButton#download_pdf {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton#download_pdf:pressed {\n"
                                        "background-color: rgb(0, 0, 0, 0);\n"
                                        "color: rgb(200, 200, 200);\n"
                                        "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Immagini/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_pdf.setIcon(icon3)
        self.download_pdf.setFlat(True)
        self.download_pdf.setObjectName("download_pdf")
        self.disdici.setGeometry(QtCore.QRect(1685, 980, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disdici.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPixelSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.disdici.setFont(font)
        self.disdici.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.disdici.setStyleSheet("QPushButton#disdici {\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#disdici:pressed {\n"
                                   "background-color: rgb(0, 0, 0, 0);\n"
                                   "color: rgb(200, 200, 200);\n"
                                   "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Immagini/disdici.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disdici.setIcon(icon4)
        self.disdici.setFlat(True)
        self.disdici.setObjectName("disdici")

        self.retranslate_ui(prenotazioni_paziente)
        QtCore.QMetaObject.connectSlotsByName(prenotazioni_paziente)

    def retranslate_ui(self, prenotazioni_paziente):
        """
        Funzione che formatta il testo degli oggetti creati all'interno della view

        :param prenotazioni_paziente: Oggetto della view che rappresenta la view stessa
        :type prenotazioni_paziente: ViewPrenotazione
        """
        _translate = QtCore.QCoreApplication.translate
        prenotazioni_paziente.setWindowTitle(_translate("prenotazioni_paziente", "Clinica Casa Alfredo"))
        self.le_mie_prenotazioni.setText(_translate("prenotazioni_paziente", "- Le Mie Prenotazioni"))
        self.nome.setText(_translate("prenotazioni_paziente", "Nome:"))
        self.cognome.setText(_translate("prenotazioni_paziente", "Cognome:"))
        self.attivita_ambulatoriale.setText(_translate("prenotazioni_paziente", "Attività ambulatoriale:"))
        self.medico.setText(_translate("prenotazioni_paziente", "Medico:"))
        self.data_e_ora.setText(_translate("prenotazioni_paziente", "Data e Ora:"))
        self.ambulatorio.setText(_translate("prenotazioni_paziente", "Ambulatorio:"))
        self.prezzo.setText(_translate("prenotazioni_paziente", "Prezzo:"))
        self.data_e_ora_prenotazione.setText(_translate("prenotazioni_paziente", "Data e Ora prenotazione:"))
        self.torna_indietro.setText(_translate("prenotazioni_paziente", "Torna Indietro"))
        self.download_pdf.setText(_translate("prenotazioni_paziente", "Download PDF"))
        self.disdici.setText(_translate("prenotazioni_paziente", "Disdici"))
