# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registrazione paziente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import openpyxl
from pathlib import Path

class Ui_registrazionePaziente(object):
    def setupUi(self, registrazionePaziente):

        file = Path('..\Database', 'Province e comuni.xlsx')
        workbook = openpyxl.load_workbook(file)
        self.sheet = workbook.active

        self.province = []

        for riga in self.sheet.iter_rows(max_row=1):
            for cella in riga:
                self.province.append(cella.value)





        registrazionePaziente.setObjectName("registrazionePaziente")
        registrazionePaziente.resize(900, 600)
        registrazionePaziente.setMinimumSize(QtCore.QSize(900, 600))
        registrazionePaziente.setMaximumSize(QtCore.QSize(900, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        registrazionePaziente.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        registrazionePaziente.setFont(font)
        registrazionePaziente.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Immagini/Logo Casa Alfredo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        registrazionePaziente.setWindowIcon(icon)
        self.logo = QtWidgets.QLabel(registrazionePaziente)
        self.logo.setGeometry(QtCore.QRect(10, 10, 35, 40))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("Immagini/Logo Casa Alfredo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.titolo = QtWidgets.QLabel(registrazionePaziente)
        self.titolo.setGeometry(QtCore.QRect(50, 14, 160, 32))
        self.titolo.setText("")
        self.titolo.setPixmap(QtGui.QPixmap("Immagini/Titolo.png"))
        self.titolo.setScaledContents(True)
        self.titolo.setObjectName("titolo")
        self.scritta = QtWidgets.QLabel(registrazionePaziente)
        self.scritta.setGeometry(QtCore.QRect(486, 320, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.scritta.setFont(font)
        self.scritta.setObjectName("scritta")
        self.registrati_button = QtWidgets.QPushButton(registrazionePaziente)
        self.registrati_button.setGeometry(QtCore.QRect(316, 482, 265, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 97, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.registrati_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.registrati_button.setFont(font)
        self.registrati_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registrati_button.setStyleSheet("QPushButton#registrati_button {\n"
"background-color: rgb(33, 97, 171);\n"
"border: 1px solid;\n"
"border-color: rgb(13, 41, 73);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#registrati_button:pressed {\n"
"background-color: rgb(13, 41, 73);\n"
"border-color: rgb(33, 97, 171);\n"
"color: rgb(200, 200, 200);\n"
"}")
        self.registrati_button.setObjectName("registrati_button")
        self.torna_indietro = QtWidgets.QPushButton(registrazionePaziente)
        self.torna_indietro.setGeometry(QtCore.QRect(730, 565, 171, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.torna_indietro.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.torna_indietro.setFont(font)
        self.torna_indietro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.torna_indietro.setStyleSheet("QPushButton#torna_indietro {\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#torna_indietro:pressed {\n"
"background-color: rgb(0, 0, 0, 0);\n"
"color: rgb(200, 200, 200);\n"
"}")
        self.torna_indietro.setFlat(True)
        self.torna_indietro.setObjectName("torna_indietro")
        self.banner = QtWidgets.QLabel(registrazionePaziente)
        self.banner.setGeometry(QtCore.QRect(0, 560, 901, 41))
        self.banner.setStyleSheet("background-color: rgb(13, 41, 73);")
        self.banner.setText("")
        self.banner.setObjectName("banner")
        self.nome_line_edit = QtWidgets.QLineEdit(registrazionePaziente)
        self.nome_line_edit.setGeometry(QtCore.QRect(166, 115, 253, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nome_line_edit.setFont(font)
        self.nome_line_edit.setStyleSheet("QLineEdit#nome_line_edit {\n"
"border: 1px solid;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"}")
        self.nome_line_edit.setPlaceholderText("")
        self.nome_line_edit.setObjectName("nome_line_edit")
        self.password_line_edit = QtWidgets.QLineEdit(registrazionePaziente)
        self.password_line_edit.setGeometry(QtCore.QRect(605, 225, 250, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.password_line_edit.setFont(font)
        self.password_line_edit.setStyleSheet("QLineEdit#password_line_edit {\n"
"border: 1px solid;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"}")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setPlaceholderText("")
        self.password_line_edit.setObjectName("password_line_edit")
        self.occhiello_button = QtWidgets.QPushButton(registrazionePaziente)
        self.occhiello_button.setGeometry(QtCore.QRect(855, 225, 40, 40))
        self.occhiello_button.setStyleSheet("QPushButton#occhiello_button:pressed {\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.occhiello_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Immagini/occhiello barrato password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.occhiello_button.setIcon(icon1)
        self.occhiello_button.setIconSize(QtCore.QSize(30, 30))
        self.occhiello_button.setFlat(True)
        self.occhiello_button.setObjectName("occhiello_button")
        self.registrazione = QtWidgets.QLabel(registrazionePaziente)
        self.registrazione.setGeometry(QtCore.QRect(219, 17, 240, 32))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.registrazione.setFont(font)
        self.registrazione.setStyleSheet("color: rgb(84, 149, 223);")
        self.registrazione.setObjectName("registrazione")
        self.dati_personali = QtWidgets.QLabel(registrazionePaziente)
        self.dati_personali.setGeometry(QtCore.QRect(150, 70, 141, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.dati_personali.setFont(font)
        self.dati_personali.setObjectName("dati_personali")
        self.nome = QtWidgets.QLabel(registrazionePaziente)
        self.nome.setGeometry(QtCore.QRect(10, 120, 66, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.nome.setFont(font)
        self.nome.setObjectName("nome")
        self.cognome = QtWidgets.QLabel(registrazionePaziente)
        self.cognome.setGeometry(QtCore.QRect(10, 165, 103, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.cognome.setFont(font)
        self.cognome.setObjectName("cognome")
        self.eta = QtWidgets.QLabel(registrazionePaziente)
        self.eta.setGeometry(QtCore.QRect(10, 255, 43, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.eta.setFont(font)
        self.eta.setObjectName("eta")
        self.sesso = QtWidgets.QLabel(registrazionePaziente)
        self.sesso.setGeometry(QtCore.QRect(10, 300, 67, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.sesso.setFont(font)
        self.sesso.setObjectName("sesso")
        self.citta_di_nascita = QtWidgets.QLabel(registrazionePaziente)
        self.citta_di_nascita.setGeometry(QtCore.QRect(10, 390, 160, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.citta_di_nascita.setFont(font)
        self.citta_di_nascita.setObjectName("citta_di_nascita")
        self.provincia = QtWidgets.QLabel(registrazionePaziente)
        self.provincia.setGeometry(QtCore.QRect(10, 345, 101, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.provincia.setFont(font)
        self.provincia.setObjectName("provincia")
        self.data_di_nascita = QtWidgets.QLabel(registrazionePaziente)
        self.data_di_nascita.setGeometry(QtCore.QRect(10, 210, 160, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.data_di_nascita.setFont(font)
        self.data_di_nascita.setObjectName("data_di_nascita")
        self.codice_fiscale = QtWidgets.QLabel(registrazionePaziente)
        self.codice_fiscale.setGeometry(QtCore.QRect(10, 435, 145, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.codice_fiscale.setFont(font)
        self.codice_fiscale.setObjectName("codice_fiscale")
        self.cognome_line_edit = QtWidgets.QLineEdit(registrazionePaziente)
        self.cognome_line_edit.setGeometry(QtCore.QRect(166, 160, 253, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cognome_line_edit.setFont(font)
        self.cognome_line_edit.setStyleSheet("QLineEdit#cognome_line_edit {\n"
"border: 1px solid;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"}")
        self.cognome_line_edit.setPlaceholderText("")
        self.cognome_line_edit.setObjectName("cognome_line_edit")
        self.codice_fiscale_line_edit = QtWidgets.QLineEdit(registrazionePaziente)
        self.codice_fiscale_line_edit.setGeometry(QtCore.QRect(175, 430, 244, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.codice_fiscale_line_edit.setFont(font)
        self.codice_fiscale_line_edit.setStyleSheet("QLineEdit#codice_fiscale_line_edit {\n"
"border: 1px solid;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"}")
        self.codice_fiscale_line_edit.setPlaceholderText("")
        self.codice_fiscale_line_edit.setObjectName("codice_fiscale_line_edit")
        self.sesso_combo_box = QtWidgets.QComboBox(registrazionePaziente)
        self.sesso_combo_box.setGeometry(QtCore.QRect(97, 295, 65, 36))
        self.sesso_combo_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.sesso_combo_box.setObjectName("sesso_combo_box")
        self.citta_di_nascita_combo_box = QtWidgets.QComboBox(registrazionePaziente)
        self.citta_di_nascita_combo_box.setGeometry(QtCore.QRect(190, 385, 229, 36))
        self.citta_di_nascita_combo_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.citta_di_nascita_combo_box.setEditable(False)
        self.citta_di_nascita_combo_box.setIconSize(QtCore.QSize(20, 20))
        self.citta_di_nascita_combo_box.setFrame(True)
        self.citta_di_nascita_combo_box.setModelColumn(0)
        self.citta_di_nascita_combo_box.setObjectName("citta_di_nascita_combo_box")






        self.provincia_combo_box = QtWidgets.QComboBox(registrazionePaziente)


        self.provincia_combo_box.addItem('Seleziona una provincia')
        self.provincia_combo_box.addItems(self.province)


        self.provincia_combo_box.setGeometry(QtCore.QRect(131, 340, 300, 36))
        self.provincia_combo_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.provincia_combo_box.setObjectName("provincia_combo_box")


        self.provincia_combo_box.activated.connect(lambda: self.lista_comuni(self.provincia_combo_box.currentText()))


        self.eta_combo_box = QtWidgets.QComboBox(registrazionePaziente)
        self.eta_combo_box.setGeometry(QtCore.QRect(72, 250, 65, 36))
        self.eta_combo_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.eta_combo_box.setObjectName("eta_combo_box")
        self.data_di_nascita_date_edit = QtWidgets.QDateEdit(registrazionePaziente)
        self.data_di_nascita_date_edit.setGeometry(QtCore.QRect(189, 205, 230, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.data_di_nascita_date_edit.setFont(font)
        self.data_di_nascita_date_edit.setCalendarPopup(True)
        self.data_di_nascita_date_edit.setCurrentSectionIndex(0)
        self.data_di_nascita_date_edit.setObjectName("data_di_nascita_date_edit")
        self.email = QtWidgets.QLabel(registrazionePaziente)
        self.email.setGeometry(QtCore.QRect(495, 120, 71, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.password = QtWidgets.QLabel(registrazionePaziente)
        self.password.setGeometry(QtCore.QRect(485, 230, 113, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.email_line_edit = QtWidgets.QLineEdit(registrazionePaziente)
        self.email_line_edit.setGeometry(QtCore.QRect(574, 115, 281, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.email_line_edit.setFont(font)
        self.email_line_edit.setStyleSheet("QLineEdit#email_line_edit {\n"
"border: 1px solid;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"}")
        self.email_line_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email_line_edit.setPlaceholderText("")
        self.email_line_edit.setObjectName("email_line_edit")
        self.dati_account = QtWidgets.QLabel(registrazionePaziente)
        self.dati_account.setGeometry(QtCore.QRect(620, 70, 141, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.dati_account.setFont(font)
        self.dati_account.setObjectName("dati_account")
        self.logo.raise_()
        self.titolo.raise_()
        self.scritta.raise_()
        self.registrati_button.raise_()
        self.banner.raise_()
        self.torna_indietro.raise_()
        self.nome_line_edit.raise_()
        self.password_line_edit.raise_()
        self.occhiello_button.raise_()
        self.registrazione.raise_()
        self.dati_personali.raise_()
        self.nome.raise_()
        self.cognome.raise_()
        self.eta.raise_()
        self.sesso.raise_()
        self.citta_di_nascita.raise_()
        self.provincia.raise_()
        self.data_di_nascita.raise_()
        self.codice_fiscale.raise_()
        self.cognome_line_edit.raise_()
        self.codice_fiscale_line_edit.raise_()
        self.sesso_combo_box.raise_()
        self.citta_di_nascita_combo_box.raise_()
        self.provincia_combo_box.raise_()
        self.eta_combo_box.raise_()
        self.data_di_nascita_date_edit.raise_()
        self.email.raise_()
        self.password.raise_()
        self.email_line_edit.raise_()
        self.dati_account.raise_()

        self.retranslateUi(registrazionePaziente)
        QtCore.QMetaObject.connectSlotsByName(registrazionePaziente)

    def retranslateUi(self, registrazionePaziente):
        _translate = QtCore.QCoreApplication.translate
        registrazionePaziente.setWindowTitle(_translate("registrazionePaziente", "Clinica Casa Alfredo"))
        self.scritta.setText(_translate("registrazionePaziente", "*Attenzione! La password deve contenere \n"
" almeno 8 caratteri, di cui almeno \n"
" 1 numero, 1 lettera Maiuscola, \n"
" 1 carattere speciale"))
        self.registrati_button.setText(_translate("registrazionePaziente", "Registrati ora"))
        self.torna_indietro.setText(_translate("registrazionePaziente", "Torna Indietro"))
        self.registrazione.setText(_translate("registrazionePaziente", "- REGISTRAZIONE"))
        self.dati_personali.setText(_translate("registrazionePaziente", "Dati Personali"))
        self.nome.setText(_translate("registrazionePaziente", "Nome:"))
        self.cognome.setText(_translate("registrazionePaziente", "Cognome:"))
        self.eta.setText(_translate("registrazionePaziente", "Età:"))
        self.sesso.setText(_translate("registrazionePaziente", "Sesso:"))
        self.citta_di_nascita.setText(_translate("registrazionePaziente", "Città di nascita:"))
        self.provincia.setText(_translate("registrazionePaziente", "Provincia:"))
        self.data_di_nascita.setText(_translate("registrazionePaziente", "Data di nascita:"))
        self.codice_fiscale.setText(_translate("registrazionePaziente", "Codice fiscale:"))
        self.email.setText(_translate("registrazionePaziente", "E-mail:"))
        self.password.setText(_translate("registrazionePaziente", "*Password:"))
        self.dati_account.setText(_translate("registrazionePaziente", "Dati Account"))

    def lista_comuni(self, provincia):

        comuni = []
        i = 0
        n = 0

        for colonna in self.sheet.iter_cols():
            i += 1
            cella = colonna[0]
            if cella.value == provincia:
                n = i

        for colonna in self.sheet.iter_cols(n, max_col=n):
            for cella in colonna:
                if cella.value is not None and cella is not colonna[0]:
                    comuni.append(cella.value)

        self.citta_di_nascita_combo_box.clear()
        self.citta_di_nascita_combo_box.addItems(comuni)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registrazionePaziente = QtWidgets.QWidget()
    ui = Ui_registrazionePaziente()
    ui.setupUi(registrazionePaziente)
    registrazionePaziente.show()
    sys.exit(app.exec_())
